Rewrite to work with kissmanga.in, add cbz format.
Astrames/kissmanga-downloader pull request #5
Opened 2020-10-11 05:40 UTC by garbled1

2020-10-15 07:53 UTC, Astrames requested changes
Hello garbled1. Thank you for your interest in this project and for your contribution!

There are some minor changes that need to be addressed, but apart from that the code looks good!

Thanks again for your contribution!

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +    chapter_number = (re.findall('\d+.?\d*', chapter_name)[0]).replace('-', '.')
The argument to `findall`, should be `\d+\.?\d*` if I'm not wrong, as this will only match patterns like "digit dot digit". The pattern written here will match "digit &lt;any character&gt; digit" which is more than what's needed.

2020-10-15 07:53 UTC, Astrames commented on README.md
> +*  Creates a ComicInfo.xml file when creating a cbz
Add a newline after this statement

2020-10-15 07:53 UTC, Astrames commented on .gitignore
> +.pyre/
Do we really need this many entries in the .gitignore file? 

This project doesn't have any CI/tests setup, and it doesn't have any Flask,Django, or any of the other stuff that this .gitignore is meant for.

Please remove these entries, only keep things that are relevant to the project (from a glance, I'm guessing there will not be any entries)

2020-10-15 07:53 UTC, Astrames commented on README.md
> +$  apt install chromium-driver
I don't have a Debian machine to test this, but does the above command `apt install chromium-chromedriver` not work for a Debian install?

2020-10-15 07:53 UTC, Astrames commented on README.md
> +`./kissmanga-download.py`
Please revert this back.

The `python file.py` syntax will work for both Windows and Linux-type OSes, however the `./file.py` will only work for Linux-type OSes.

It may not be immediately obvious to Windows users what this line is, hence it's preferred to keep the `python file.py` usage

And the ability to run it as a executable script via shebang is mentioned on line 43.

If needed, you may mention how Linux users might have to user `python3` instead of `python`.

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +# from selenium.webdriver.support.ui import Select
We can remove this comment if it's not needed

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +    # select = Select(drop_down_list)
Remove if unneeded

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +    # # Selecting the 'All Pages' option
Remove one `#`

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +    # select.select_by_value('List style')
Removed if unneeded

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +    while (nrof_urls == 0 and tries > 1):
We can remove the parentheses around the `while` invariant as we not in  C/Java :D

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +                zfile = zipfile.ZipFile(cbz_filename, "w")
Use a context manager to interact with files. It's safer and more clear

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +    while (nrof_urls == 0 and tries > 1):
Correct me if I'm wrong but the condition in `while` should probably be `nrof_urls == 0 and tries > 0`, as in 0 instead of 1

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +    if nrof_urls == 0:
If the number of chapters is 0, it doesn't necessarily mean that the application was unable to connect to the website. 


I think either the `print` function argument should be changed to say `No chapters were found` 

OR

The condition needs to check whether or not the application connected to the website properly as opposed to just checking the length of the chapter urls list.

2020-10-15 07:53 UTC, Astrames commented on README.md
> +*  Creates a ComicInfo.xml file when creating a cbz
I'm not sure exactly what purpose the XML file serving.

If you elaborate on that part, it'd be great. Maybe even adding information about it in the README.md

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +        pass
We should probably `print` something as a form of logging in the `except` clauses of these `try...except` blocks. Applies for all `except` clauses which have `pass`

2020-10-15 07:53 UTC, Astrames commented on kissmanga-downloader.py
> +    xf = open(fp, "wb")
Try to use context managers when interacting with files, as that will be safer if any exceptions occur.

2020-10-16 04:42 UTC, garbled1 commented on kissmanga-downloader.py
> +    chapter_number = (re.findall('\d+.?\d*', chapter_name)[0]).replace('-', '.')
The problem I kept hitting was stuff like 25-2 written instead of 25.2 in the chapters..  I ended up tweaking this a little in my code though, because I was ending up with a few that transformed to '25.'

2020-10-16 04:43 UTC, garbled1 commented on README.md
> +$  apt install chromium-driver
It does not, I run debian, thats how I had to install it.

2020-10-16 04:44 UTC, garbled1 commented on kissmanga-downloader.py
> +    if nrof_urls == 0:
Yeah.. so.. I keep getting this odd problem where it connects and finds nothing, and then if you run again, it finds all the URLs..  I've been unable to figure out why exactly...

2020-10-16 04:46 UTC, garbled1 commented on kissmanga-downloader.py
> +        pass
For some of these, the idea is that IF the manga has "Writer" listed, we create a writer XML segment, but if not, we really do nothing, we don't want that XML tag at all in the resulting xml, so we just silently skip.. I guess we could say "no writer found", but, it ends up not being really an error, it's just they didn't fill that in on the site.

2020-10-16 04:47 UTC, garbled1 commented
Yeah.. some good comments.. I'll clean the ones up that I haven't commented on directly..

2020-10-20 13:20 UTC, garbled1 commented
Should be good to go.

2020-10-25 13:23 UTC, Astrames approved these changes
This is good to go. For those minor comments, I guess we could make issues which tackle them; but it's fine for now.

Thanks again for your interest in and contribution to this project.

2020-10-25 13:24 UTC, merged